# Generated by Django 4.2 on 2025-09-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sysrole',
            table='sys_role',
        ),
    ]
